version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node-fetch"
      - dependency-name: "node-fetch"
      - dependency-name: "camelcase"
      - dependency-name: "@angular-devkit/build-angular"
      - dependency-name: "@angular/animations"
      - dependency-name: "@angular/cli"
      - dependency-name: "@angular/common"
      - dependency-name: "@angular/compiler"
      - dependency-name: "@angular/compiler-cli"
      - dependency-name: "@angular/core"
      - dependency-name: "@angular/forms"
      - dependency-name: "@angular/platform-browser"
      - dependency-name: "@angular/platform-browser-dynamic"
      - dependency-name: "@angular/router"
      - dependency-name: "typescript"